package com.shd.model.pojo;

import java.util.Date;

public class Chinese extends MybatisObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinese.chinese_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String chineseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinese.chinese_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String chineseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinese.py_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String pyAbb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinese.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinese.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinese.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinese.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinese.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String delState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinese.chinese_id
     *
     * @return the value of chinese.chinese_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getChineseId() {
        return chineseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinese.chinese_id
     *
     * @param chineseId the value for chinese.chinese_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setChineseId(String chineseId) {
        this.chineseId = chineseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinese.chinese_name
     *
     * @return the value of chinese.chinese_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getChineseName() {
        return chineseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinese.chinese_name
     *
     * @param chineseName the value for chinese.chinese_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinese.py_abb
     *
     * @return the value of chinese.py_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getPyAbb() {
        return pyAbb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinese.py_abb
     *
     * @param pyAbb the value for chinese.py_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPyAbb(String pyAbb) {
        this.pyAbb = pyAbb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinese.create_user
     *
     * @return the value of chinese.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinese.create_user
     *
     * @param createUser the value for chinese.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinese.create_time
     *
     * @return the value of chinese.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinese.create_time
     *
     * @param createTime the value for chinese.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinese.modify_user
     *
     * @return the value of chinese.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinese.modify_user
     *
     * @param modifyUser the value for chinese.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinese.modify_time
     *
     * @return the value of chinese.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinese.modify_time
     *
     * @param modifyTime the value for chinese.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinese.del_state
     *
     * @return the value of chinese.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinese.del_state
     *
     * @param delState the value for chinese.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setDelState(String delState) {
        this.delState = delState;
    }
}