package com.shd.model.pojo;

import java.util.Date;

public class Medicine extends MybatisObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.medicine_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String medicineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.pinyin_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String pinyinAbb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.specs
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String specs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.unit
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.medicine_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String medicineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.medicine_character
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String medicineCharacter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.classify
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String classify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String delState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.medicine_id
     *
     * @return the value of medicine.medicine_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getMedicineId() {
        return medicineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.medicine_id
     *
     * @param medicineId the value for medicine.medicine_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setMedicineId(String medicineId) {
        this.medicineId = medicineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.pinyin_abb
     *
     * @return the value of medicine.pinyin_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getPinyinAbb() {
        return pinyinAbb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.pinyin_abb
     *
     * @param pinyinAbb the value for medicine.pinyin_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPinyinAbb(String pinyinAbb) {
        this.pinyinAbb = pinyinAbb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.specs
     *
     * @return the value of medicine.specs
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getSpecs() {
        return specs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.specs
     *
     * @param specs the value for medicine.specs
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setSpecs(String specs) {
        this.specs = specs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.unit
     *
     * @return the value of medicine.unit
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.unit
     *
     * @param unit the value for medicine.unit
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.medicine_name
     *
     * @return the value of medicine.medicine_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getMedicineName() {
        return medicineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.medicine_name
     *
     * @param medicineName the value for medicine.medicine_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setMedicineName(String medicineName) {
        this.medicineName = medicineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.medicine_character
     *
     * @return the value of medicine.medicine_character
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getMedicineCharacter() {
        return medicineCharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.medicine_character
     *
     * @param medicineCharacter the value for medicine.medicine_character
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setMedicineCharacter(String medicineCharacter) {
        this.medicineCharacter = medicineCharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.classify
     *
     * @return the value of medicine.classify
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.classify
     *
     * @param classify the value for medicine.classify
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setClassify(String classify) {
        this.classify = classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.create_user
     *
     * @return the value of medicine.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.create_user
     *
     * @param createUser the value for medicine.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.create_time
     *
     * @return the value of medicine.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.create_time
     *
     * @param createTime the value for medicine.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.modify_user
     *
     * @return the value of medicine.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.modify_user
     *
     * @param modifyUser the value for medicine.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.modify_time
     *
     * @return the value of medicine.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.modify_time
     *
     * @param modifyTime the value for medicine.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.del_state
     *
     * @return the value of medicine.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.del_state
     *
     * @param delState the value for medicine.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setDelState(String delState) {
        this.delState = delState;
    }
}