package com.shd.model.pojo;

public class MedicineWithBLOBs extends Medicine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.medicine_introduce
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String medicineIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.notice
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String notice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.medicine_introduce
     *
     * @return the value of medicine.medicine_introduce
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getMedicineIntroduce() {
        return medicineIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.medicine_introduce
     *
     * @param medicineIntroduce the value for medicine.medicine_introduce
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setMedicineIntroduce(String medicineIntroduce) {
        this.medicineIntroduce = medicineIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.notice
     *
     * @return the value of medicine.notice
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.notice
     *
     * @param notice the value for medicine.notice
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setNotice(String notice) {
        this.notice = notice;
    }
}