package com.shd.model.pojo;

import java.util.Date;

public class Patient extends MybatisObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patient_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patient_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String patientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patient_birthday
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date patientBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patient_age
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Integer patientAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patient_genderId
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String patientGenderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.pres_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String presId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String delState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patient_id
     *
     * @return the value of patient.patient_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patient_id
     *
     * @param patientId the value for patient.patient_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patient_name
     *
     * @return the value of patient.patient_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patient_name
     *
     * @param patientName the value for patient.patient_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patient_birthday
     *
     * @return the value of patient.patient_birthday
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getPatientBirthday() {
        return patientBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patient_birthday
     *
     * @param patientBirthday the value for patient.patient_birthday
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPatientBirthday(Date patientBirthday) {
        this.patientBirthday = patientBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patient_age
     *
     * @return the value of patient.patient_age
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Integer getPatientAge() {
        return patientAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patient_age
     *
     * @param patientAge the value for patient.patient_age
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPatientAge(Integer patientAge) {
        this.patientAge = patientAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patient_genderId
     *
     * @return the value of patient.patient_genderId
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getPatientGenderid() {
        return patientGenderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patient_genderId
     *
     * @param patientGenderid the value for patient.patient_genderId
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPatientGenderid(String patientGenderid) {
        this.patientGenderid = patientGenderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.pres_id
     *
     * @return the value of patient.pres_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getPresId() {
        return presId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.pres_id
     *
     * @param presId the value for patient.pres_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPresId(String presId) {
        this.presId = presId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.create_user
     *
     * @return the value of patient.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.create_user
     *
     * @param createUser the value for patient.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.create_time
     *
     * @return the value of patient.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.create_time
     *
     * @param createTime the value for patient.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.modify_user
     *
     * @return the value of patient.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.modify_user
     *
     * @param modifyUser the value for patient.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.modify_time
     *
     * @return the value of patient.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.modify_time
     *
     * @param modifyTime the value for patient.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.del_state
     *
     * @return the value of patient.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.del_state
     *
     * @param delState the value for patient.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setDelState(String delState) {
        this.delState = delState;
    }
}