package com.shd.model.pojo;

import java.util.Date;

public class Prescription extends MybatisObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.prescription_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String prescriptionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.visits
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Integer visits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.iusage
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String iusage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.py_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String pyAbb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Treatment_cycle
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String treatmentCycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.visit_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date visitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String delState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.prescription_id
     *
     * @return the value of prescription.prescription_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getPrescriptionId() {
        return prescriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.prescription_id
     *
     * @param prescriptionId the value for prescription.prescription_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPrescriptionId(String prescriptionId) {
        this.prescriptionId = prescriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.visits
     *
     * @return the value of prescription.visits
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Integer getVisits() {
        return visits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.visits
     *
     * @param visits the value for prescription.visits
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setVisits(Integer visits) {
        this.visits = visits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.iusage
     *
     * @return the value of prescription.iusage
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getIusage() {
        return iusage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.iusage
     *
     * @param iusage the value for prescription.iusage
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setIusage(String iusage) {
        this.iusage = iusage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.py_abb
     *
     * @return the value of prescription.py_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getPyAbb() {
        return pyAbb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.py_abb
     *
     * @param pyAbb the value for prescription.py_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPyAbb(String pyAbb) {
        this.pyAbb = pyAbb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Treatment_cycle
     *
     * @return the value of prescription.Treatment_cycle
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getTreatmentCycle() {
        return treatmentCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Treatment_cycle
     *
     * @param treatmentCycle the value for prescription.Treatment_cycle
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setTreatmentCycle(String treatmentCycle) {
        this.treatmentCycle = treatmentCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.visit_time
     *
     * @return the value of prescription.visit_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.visit_time
     *
     * @param visitTime the value for prescription.visit_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setVisitTime(Date visitTime) {
        this.visitTime = visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.create_user
     *
     * @return the value of prescription.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.create_user
     *
     * @param createUser the value for prescription.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.create_time
     *
     * @return the value of prescription.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.create_time
     *
     * @param createTime the value for prescription.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.modify_user
     *
     * @return the value of prescription.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.modify_user
     *
     * @param modifyUser the value for prescription.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.modify_time
     *
     * @return the value of prescription.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.modify_time
     *
     * @param modifyTime the value for prescription.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.del_state
     *
     * @return the value of prescription.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.del_state
     *
     * @param delState the value for prescription.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setDelState(String delState) {
        this.delState = delState;
    }
}