package com.shd.model.pojo;

public class PrescriptionWithBLOBs extends Prescription {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.prescription_introduce
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String prescriptionIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.western_diagnosis
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String westernDiagnosis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.pname
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.disease
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String disease;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.medical_history
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String medicalHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.equipment_inspection
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String equipmentInspection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.physical_examination
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String physicalExamination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.west_medicines
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String westMedicines;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.medicines
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String medicines;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.prescription_introduce
     *
     * @return the value of prescription.prescription_introduce
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getPrescriptionIntroduce() {
        return prescriptionIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.prescription_introduce
     *
     * @param prescriptionIntroduce the value for prescription.prescription_introduce
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPrescriptionIntroduce(String prescriptionIntroduce) {
        this.prescriptionIntroduce = prescriptionIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.western_diagnosis
     *
     * @return the value of prescription.western_diagnosis
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getWesternDiagnosis() {
        return westernDiagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.western_diagnosis
     *
     * @param westernDiagnosis the value for prescription.western_diagnosis
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setWesternDiagnosis(String westernDiagnosis) {
        this.westernDiagnosis = westernDiagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.pname
     *
     * @return the value of prescription.pname
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.pname
     *
     * @param pname the value for prescription.pname
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.disease
     *
     * @return the value of prescription.disease
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getDisease() {
        return disease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.disease
     *
     * @param disease the value for prescription.disease
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setDisease(String disease) {
        this.disease = disease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.medical_history
     *
     * @return the value of prescription.medical_history
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getMedicalHistory() {
        return medicalHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.medical_history
     *
     * @param medicalHistory the value for prescription.medical_history
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setMedicalHistory(String medicalHistory) {
        this.medicalHistory = medicalHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.equipment_inspection
     *
     * @return the value of prescription.equipment_inspection
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getEquipmentInspection() {
        return equipmentInspection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.equipment_inspection
     *
     * @param equipmentInspection the value for prescription.equipment_inspection
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setEquipmentInspection(String equipmentInspection) {
        this.equipmentInspection = equipmentInspection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.physical_examination
     *
     * @return the value of prescription.physical_examination
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getPhysicalExamination() {
        return physicalExamination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.physical_examination
     *
     * @param physicalExamination the value for prescription.physical_examination
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPhysicalExamination(String physicalExamination) {
        this.physicalExamination = physicalExamination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.west_medicines
     *
     * @return the value of prescription.west_medicines
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getWestMedicines() {
        return westMedicines;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.west_medicines
     *
     * @param westMedicines the value for prescription.west_medicines
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setWestMedicines(String westMedicines) {
        this.westMedicines = westMedicines;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.medicines
     *
     * @return the value of prescription.medicines
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getMedicines() {
        return medicines;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.medicines
     *
     * @param medicines the value for prescription.medicines
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setMedicines(String medicines) {
        this.medicines = medicines;
    }
}