package com.shd.model.pojo;

import java.util.Date;

public class SysCfg extends MybatisObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cfg.CFG_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String cfgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cfg.CFG_CODE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String cfgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cfg.CFG_VALUE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String cfgValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cfg.CFG_DESC
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String cfgDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cfg.RECORD_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String recordState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cfg.CREATE_USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cfg.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cfg.MODIFY_USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String modifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cfg.MODIFY_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cfg.CFG_ID
     *
     * @return the value of sys_cfg.CFG_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCfgId() {
        return cfgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cfg.CFG_ID
     *
     * @param cfgId the value for sys_cfg.CFG_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCfgId(String cfgId) {
        this.cfgId = cfgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cfg.CFG_CODE
     *
     * @return the value of sys_cfg.CFG_CODE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCfgCode() {
        return cfgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cfg.CFG_CODE
     *
     * @param cfgCode the value for sys_cfg.CFG_CODE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCfgCode(String cfgCode) {
        this.cfgCode = cfgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cfg.CFG_VALUE
     *
     * @return the value of sys_cfg.CFG_VALUE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCfgValue() {
        return cfgValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cfg.CFG_VALUE
     *
     * @param cfgValue the value for sys_cfg.CFG_VALUE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCfgValue(String cfgValue) {
        this.cfgValue = cfgValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cfg.CFG_DESC
     *
     * @return the value of sys_cfg.CFG_DESC
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCfgDesc() {
        return cfgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cfg.CFG_DESC
     *
     * @param cfgDesc the value for sys_cfg.CFG_DESC
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCfgDesc(String cfgDesc) {
        this.cfgDesc = cfgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cfg.RECORD_STATE
     *
     * @return the value of sys_cfg.RECORD_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getRecordState() {
        return recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cfg.RECORD_STATE
     *
     * @param recordState the value for sys_cfg.RECORD_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setRecordState(String recordState) {
        this.recordState = recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cfg.CREATE_USER_ID
     *
     * @return the value of sys_cfg.CREATE_USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cfg.CREATE_USER_ID
     *
     * @param createUserId the value for sys_cfg.CREATE_USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cfg.CREATE_TIME
     *
     * @return the value of sys_cfg.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cfg.CREATE_TIME
     *
     * @param createTime the value for sys_cfg.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cfg.MODIFY_USER_ID
     *
     * @return the value of sys_cfg.MODIFY_USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cfg.MODIFY_USER_ID
     *
     * @param modifyUserId the value for sys_cfg.MODIFY_USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setModifyUserId(String modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cfg.MODIFY_TIME
     *
     * @return the value of sys_cfg.MODIFY_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cfg.MODIFY_TIME
     *
     * @param modifyTime the value for sys_cfg.MODIFY_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}