package com.shd.model.pojo;

import java.util.Date;

public class SysLog extends MybatisObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.LOG_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.LOG_TYPE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String logType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.LOG_DETAILS
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String logDetails;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.DEL_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String delState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.CREATE_USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.UPDATE_USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.LOG_ID
     *
     * @return the value of sys_log.LOG_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.LOG_ID
     *
     * @param logId the value for sys_log.LOG_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setLogId(String logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.LOG_TYPE
     *
     * @return the value of sys_log.LOG_TYPE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.LOG_TYPE
     *
     * @param logType the value for sys_log.LOG_TYPE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setLogType(String logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.LOG_DETAILS
     *
     * @return the value of sys_log.LOG_DETAILS
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getLogDetails() {
        return logDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.LOG_DETAILS
     *
     * @param logDetails the value for sys_log.LOG_DETAILS
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setLogDetails(String logDetails) {
        this.logDetails = logDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.DEL_STATE
     *
     * @return the value of sys_log.DEL_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.DEL_STATE
     *
     * @param delState the value for sys_log.DEL_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setDelState(String delState) {
        this.delState = delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.CREATE_USER_ID
     *
     * @return the value of sys_log.CREATE_USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.CREATE_USER_ID
     *
     * @param createUserId the value for sys_log.CREATE_USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.CREATE_TIME
     *
     * @return the value of sys_log.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.CREATE_TIME
     *
     * @param createTime the value for sys_log.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.UPDATE_USER_ID
     *
     * @return the value of sys_log.UPDATE_USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.UPDATE_USER_ID
     *
     * @param updateUserId the value for sys_log.UPDATE_USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.UPDATE_TIME
     *
     * @return the value of sys_log.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.UPDATE_TIME
     *
     * @param updateTime the value for sys_log.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}