package com.shd.model.pojo;

import java.util.Date;

public class SysMenu extends MybatisObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_NAME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_PARENT_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String menuParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.IS_LEAF
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String isLeaf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_URL
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_ICON_URL
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String menuIconUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_DESC
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String menuDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.SORT_KEY
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Integer sortKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.RECORD_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.CREATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.UPDATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_ID
     *
     * @return the value of sys_menu.MENU_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_ID
     *
     * @param menuId the value for sys_menu.MENU_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_NAME
     *
     * @return the value of sys_menu.MENU_NAME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_NAME
     *
     * @param menuName the value for sys_menu.MENU_NAME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_PARENT_ID
     *
     * @return the value of sys_menu.MENU_PARENT_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getMenuParentId() {
        return menuParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_PARENT_ID
     *
     * @param menuParentId the value for sys_menu.MENU_PARENT_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setMenuParentId(String menuParentId) {
        this.menuParentId = menuParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.IS_LEAF
     *
     * @return the value of sys_menu.IS_LEAF
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.IS_LEAF
     *
     * @param isLeaf the value for sys_menu.IS_LEAF
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setIsLeaf(String isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_URL
     *
     * @return the value of sys_menu.MENU_URL
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_URL
     *
     * @param menuUrl the value for sys_menu.MENU_URL
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_ICON_URL
     *
     * @return the value of sys_menu.MENU_ICON_URL
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getMenuIconUrl() {
        return menuIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_ICON_URL
     *
     * @param menuIconUrl the value for sys_menu.MENU_ICON_URL
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setMenuIconUrl(String menuIconUrl) {
        this.menuIconUrl = menuIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_DESC
     *
     * @return the value of sys_menu.MENU_DESC
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_DESC
     *
     * @param menuDesc the value for sys_menu.MENU_DESC
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.SORT_KEY
     *
     * @return the value of sys_menu.SORT_KEY
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Integer getSortKey() {
        return sortKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.SORT_KEY
     *
     * @param sortKey the value for sys_menu.SORT_KEY
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setSortKey(Integer sortKey) {
        this.sortKey = sortKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.RECORD_ID
     *
     * @return the value of sys_menu.RECORD_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.RECORD_ID
     *
     * @param recordId the value for sys_menu.RECORD_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.CREATE_USER
     *
     * @return the value of sys_menu.CREATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.CREATE_USER
     *
     * @param createUser the value for sys_menu.CREATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.CREATE_TIME
     *
     * @return the value of sys_menu.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.CREATE_TIME
     *
     * @param createTime the value for sys_menu.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.UPDATE_USER
     *
     * @return the value of sys_menu.UPDATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.UPDATE_USER
     *
     * @param updateUser the value for sys_menu.UPDATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.UPDATE_TIME
     *
     * @return the value of sys_menu.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.UPDATE_TIME
     *
     * @param updateTime the value for sys_menu.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}