package com.shd.model.pojo;

import java.util.Date;

public class SysUserRole extends MybatisObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.RECORD_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.ROLE_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.RECORD_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String recordState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.CREATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.UPDATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.RECORD_ID
     *
     * @return the value of sys_user_role.RECORD_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.RECORD_ID
     *
     * @param recordId the value for sys_user_role.RECORD_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.USER_ID
     *
     * @return the value of sys_user_role.USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.USER_ID
     *
     * @param userId the value for sys_user_role.USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.ROLE_ID
     *
     * @return the value of sys_user_role.ROLE_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.ROLE_ID
     *
     * @param roleId the value for sys_user_role.ROLE_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.RECORD_STATE
     *
     * @return the value of sys_user_role.RECORD_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getRecordState() {
        return recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.RECORD_STATE
     *
     * @param recordState the value for sys_user_role.RECORD_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setRecordState(String recordState) {
        this.recordState = recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.CREATE_USER
     *
     * @return the value of sys_user_role.CREATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.CREATE_USER
     *
     * @param createUser the value for sys_user_role.CREATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.CREATE_TIME
     *
     * @return the value of sys_user_role.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.CREATE_TIME
     *
     * @param createTime the value for sys_user_role.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.UPDATE_USER
     *
     * @return the value of sys_user_role.UPDATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.UPDATE_USER
     *
     * @param updateUser the value for sys_user_role.UPDATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.UPDATE_TIME
     *
     * @return the value of sys_user_role.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.UPDATE_TIME
     *
     * @param updateTime the value for sys_user_role.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}