package com.shd.model.pojo;

import java.util.Date;

public class SysUser extends MybatisObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_ACC
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String userAcc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_PWD
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_NAME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.POWER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String power;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.GENDER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String genderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.NATION_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String nationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.NATIVE_PLACE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String nativePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.EDUCATION_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String educationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.SCHOOL
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.MAJOR
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_BIRTHDAY
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date userBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CHINA_ID_NO
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String chinaIdNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_MOBILE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String userMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_PHONE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_EMAIL
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.JOB_NUM
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String jobNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_DESC
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String userDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.RECORD_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String recordState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CREATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.UPDATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_ID
     *
     * @return the value of sys_user.USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_ID
     *
     * @param userId the value for sys_user.USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_ACC
     *
     * @return the value of sys_user.USER_ACC
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUserAcc() {
        return userAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_ACC
     *
     * @param userAcc the value for sys_user.USER_ACC
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUserAcc(String userAcc) {
        this.userAcc = userAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_PWD
     *
     * @return the value of sys_user.USER_PWD
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_PWD
     *
     * @param userPwd the value for sys_user.USER_PWD
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_NAME
     *
     * @return the value of sys_user.USER_NAME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_NAME
     *
     * @param userName the value for sys_user.USER_NAME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.POWER
     *
     * @return the value of sys_user.POWER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.POWER
     *
     * @param power the value for sys_user.POWER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPower(String power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.GENDER_ID
     *
     * @return the value of sys_user.GENDER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getGenderId() {
        return genderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.GENDER_ID
     *
     * @param genderId the value for sys_user.GENDER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setGenderId(String genderId) {
        this.genderId = genderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.NATION_ID
     *
     * @return the value of sys_user.NATION_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getNationId() {
        return nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.NATION_ID
     *
     * @param nationId the value for sys_user.NATION_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setNationId(String nationId) {
        this.nationId = nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.NATIVE_PLACE
     *
     * @return the value of sys_user.NATIVE_PLACE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.NATIVE_PLACE
     *
     * @param nativePlace the value for sys_user.NATIVE_PLACE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.EDUCATION_ID
     *
     * @return the value of sys_user.EDUCATION_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getEducationId() {
        return educationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.EDUCATION_ID
     *
     * @param educationId the value for sys_user.EDUCATION_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setEducationId(String educationId) {
        this.educationId = educationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.SCHOOL
     *
     * @return the value of sys_user.SCHOOL
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.SCHOOL
     *
     * @param school the value for sys_user.SCHOOL
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.MAJOR
     *
     * @return the value of sys_user.MAJOR
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.MAJOR
     *
     * @param major the value for sys_user.MAJOR
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_BIRTHDAY
     *
     * @return the value of sys_user.USER_BIRTHDAY
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_BIRTHDAY
     *
     * @param userBirthday the value for sys_user.USER_BIRTHDAY
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CHINA_ID_NO
     *
     * @return the value of sys_user.CHINA_ID_NO
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getChinaIdNo() {
        return chinaIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CHINA_ID_NO
     *
     * @param chinaIdNo the value for sys_user.CHINA_ID_NO
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setChinaIdNo(String chinaIdNo) {
        this.chinaIdNo = chinaIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_MOBILE
     *
     * @return the value of sys_user.USER_MOBILE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_MOBILE
     *
     * @param userMobile the value for sys_user.USER_MOBILE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_PHONE
     *
     * @return the value of sys_user.USER_PHONE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_PHONE
     *
     * @param userPhone the value for sys_user.USER_PHONE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_EMAIL
     *
     * @return the value of sys_user.USER_EMAIL
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_EMAIL
     *
     * @param userEmail the value for sys_user.USER_EMAIL
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.JOB_NUM
     *
     * @return the value of sys_user.JOB_NUM
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getJobNum() {
        return jobNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.JOB_NUM
     *
     * @param jobNum the value for sys_user.JOB_NUM
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setJobNum(String jobNum) {
        this.jobNum = jobNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_DESC
     *
     * @return the value of sys_user.USER_DESC
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUserDesc() {
        return userDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_DESC
     *
     * @param userDesc the value for sys_user.USER_DESC
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUserDesc(String userDesc) {
        this.userDesc = userDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.RECORD_STATE
     *
     * @return the value of sys_user.RECORD_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getRecordState() {
        return recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.RECORD_STATE
     *
     * @param recordState the value for sys_user.RECORD_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setRecordState(String recordState) {
        this.recordState = recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CREATE_USER
     *
     * @return the value of sys_user.CREATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CREATE_USER
     *
     * @param createUser the value for sys_user.CREATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CREATE_TIME
     *
     * @return the value of sys_user.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CREATE_TIME
     *
     * @param createTime the value for sys_user.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.UPDATE_USER
     *
     * @return the value of sys_user.UPDATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.UPDATE_USER
     *
     * @param updateUser the value for sys_user.UPDATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.UPDATE_TIME
     *
     * @return the value of sys_user.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.UPDATE_TIME
     *
     * @param updateTime the value for sys_user.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}