package com.shd.model.pojo;

import java.util.Date;

public class SysUserMenu extends MybatisObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_menu.USER_MENU_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String userMenuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_menu.USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_menu.MENU_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_menu.DEL_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String delState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_menu.CREATE_USR
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String createUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_menu.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_menu.UPDATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_menu.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_menu.USER_MENU_ID
     *
     * @return the value of sys_user_menu.USER_MENU_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUserMenuId() {
        return userMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_menu.USER_MENU_ID
     *
     * @param userMenuId the value for sys_user_menu.USER_MENU_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUserMenuId(String userMenuId) {
        this.userMenuId = userMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_menu.USER_ID
     *
     * @return the value of sys_user_menu.USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_menu.USER_ID
     *
     * @param userId the value for sys_user_menu.USER_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_menu.MENU_ID
     *
     * @return the value of sys_user_menu.MENU_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_menu.MENU_ID
     *
     * @param menuId the value for sys_user_menu.MENU_ID
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_menu.DEL_STATE
     *
     * @return the value of sys_user_menu.DEL_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_menu.DEL_STATE
     *
     * @param delState the value for sys_user_menu.DEL_STATE
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setDelState(String delState) {
        this.delState = delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_menu.CREATE_USR
     *
     * @return the value of sys_user_menu.CREATE_USR
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCreateUsr() {
        return createUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_menu.CREATE_USR
     *
     * @param createUsr the value for sys_user_menu.CREATE_USR
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateUsr(String createUsr) {
        this.createUsr = createUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_menu.CREATE_TIME
     *
     * @return the value of sys_user_menu.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_menu.CREATE_TIME
     *
     * @param createTime the value for sys_user_menu.CREATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_menu.UPDATE_USER
     *
     * @return the value of sys_user_menu.UPDATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_menu.UPDATE_USER
     *
     * @param updateUser the value for sys_user_menu.UPDATE_USER
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_menu.UPDATE_TIME
     *
     * @return the value of sys_user_menu.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_menu.UPDATE_TIME
     *
     * @param updateTime the value for sys_user_menu.UPDATE_TIME
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}