package com.shd.model.pojo;

import java.util.Date;

public class West extends MybatisObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column west.west_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String westId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column west.west_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String westName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column west.py_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String pyAbb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column west.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column west.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column west.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column west.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column west.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String delState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column west.west_id
     *
     * @return the value of west.west_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getWestId() {
        return westId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column west.west_id
     *
     * @param westId the value for west.west_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setWestId(String westId) {
        this.westId = westId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column west.west_name
     *
     * @return the value of west.west_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getWestName() {
        return westName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column west.west_name
     *
     * @param westName the value for west.west_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setWestName(String westName) {
        this.westName = westName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column west.py_abb
     *
     * @return the value of west.py_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getPyAbb() {
        return pyAbb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column west.py_abb
     *
     * @param pyAbb the value for west.py_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPyAbb(String pyAbb) {
        this.pyAbb = pyAbb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column west.create_user
     *
     * @return the value of west.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column west.create_user
     *
     * @param createUser the value for west.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column west.create_time
     *
     * @return the value of west.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column west.create_time
     *
     * @param createTime the value for west.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column west.modify_user
     *
     * @return the value of west.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column west.modify_user
     *
     * @param modifyUser the value for west.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column west.modify_time
     *
     * @return the value of west.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column west.modify_time
     *
     * @param modifyTime the value for west.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column west.del_state
     *
     * @return the value of west.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column west.del_state
     *
     * @param delState the value for west.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setDelState(String delState) {
        this.delState = delState;
    }
}