package com.shd.model.pojo;

import java.util.Date;

public class Zybm extends MybatisObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zybm.zybm_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String zybmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zybm.zybm_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String zybmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zybm.py_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String pyAbb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zybm.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zybm.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zybm.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zybm.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zybm.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    private String delState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zybm.zybm_id
     *
     * @return the value of zybm.zybm_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getZybmId() {
        return zybmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zybm.zybm_id
     *
     * @param zybmId the value for zybm.zybm_id
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setZybmId(String zybmId) {
        this.zybmId = zybmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zybm.zybm_name
     *
     * @return the value of zybm.zybm_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getZybmName() {
        return zybmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zybm.zybm_name
     *
     * @param zybmName the value for zybm.zybm_name
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setZybmName(String zybmName) {
        this.zybmName = zybmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zybm.py_abb
     *
     * @return the value of zybm.py_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getPyAbb() {
        return pyAbb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zybm.py_abb
     *
     * @param pyAbb the value for zybm.py_abb
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setPyAbb(String pyAbb) {
        this.pyAbb = pyAbb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zybm.create_user
     *
     * @return the value of zybm.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zybm.create_user
     *
     * @param createUser the value for zybm.create_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zybm.create_time
     *
     * @return the value of zybm.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zybm.create_time
     *
     * @param createTime the value for zybm.create_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zybm.modify_user
     *
     * @return the value of zybm.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zybm.modify_user
     *
     * @param modifyUser the value for zybm.modify_user
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zybm.modify_time
     *
     * @return the value of zybm.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zybm.modify_time
     *
     * @param modifyTime the value for zybm.modify_time
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zybm.del_state
     *
     * @return the value of zybm.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public String getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zybm.del_state
     *
     * @param delState the value for zybm.del_state
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    public void setDelState(String delState) {
        this.delState = delState;
    }
}