package com.shd.dao.mapper;

import com.shd.model.pojo.Chinese;
import com.shd.model.pojo.ChineseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChineseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinese
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    long countByExample(ChineseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinese
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int deleteByExample(ChineseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinese
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int deleteByPrimaryKey(String chineseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinese
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int insert(Chinese record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinese
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int insertSelective(Chinese record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinese
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    List<Chinese> selectByExample(ChineseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinese
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    Chinese selectByPrimaryKey(String chineseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinese
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Chinese record, @Param("example") ChineseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinese
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByExample(@Param("record") Chinese record, @Param("example") ChineseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinese
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByPrimaryKeySelective(Chinese record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinese
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByPrimaryKey(Chinese record);
}