package com.shd.dao.mapper;

import com.shd.model.pojo.Prescription;
import com.shd.model.pojo.PrescriptionExample;
import com.shd.model.pojo.PrescriptionWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    long countByExample(PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int deleteByExample(PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int deleteByPrimaryKey(String prescriptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int insert(PrescriptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int insertSelective(PrescriptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    List<PrescriptionWithBLOBs> selectByExampleWithBLOBs(PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    List<Prescription> selectByExample(PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    PrescriptionWithBLOBs selectByPrimaryKey(String prescriptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") PrescriptionWithBLOBs record, @Param("example") PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") PrescriptionWithBLOBs record, @Param("example") PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByExample(@Param("record") Prescription record, @Param("example") PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByPrimaryKeySelective(PrescriptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(PrescriptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByPrimaryKey(Prescription record);
}