package com.shd.dao.mapper;

import com.shd.model.pojo.SysUserMenu;
import com.shd.model.pojo.SysUserMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    long countByExample(SysUserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int deleteByExample(SysUserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int deleteByPrimaryKey(String userMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int insert(SysUserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int insertSelective(SysUserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    List<SysUserMenu> selectByExample(SysUserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    SysUserMenu selectByPrimaryKey(String userMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysUserMenu record, @Param("example") SysUserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByExample(@Param("record") SysUserMenu record, @Param("example") SysUserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByPrimaryKeySelective(SysUserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByPrimaryKey(SysUserMenu record);
}