package com.shd.dao.mapper;

import com.shd.model.pojo.West;
import com.shd.model.pojo.WestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table west
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    long countByExample(WestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table west
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int deleteByExample(WestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table west
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int deleteByPrimaryKey(String westId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table west
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int insert(West record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table west
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int insertSelective(West record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table west
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    List<West> selectByExample(WestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table west
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    West selectByPrimaryKey(String westId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table west
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") West record, @Param("example") WestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table west
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByExample(@Param("record") West record, @Param("example") WestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table west
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByPrimaryKeySelective(West record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table west
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByPrimaryKey(West record);
}