package com.shd.dao.mapper;

import com.shd.model.pojo.Zybm;
import com.shd.model.pojo.ZybmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZybmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zybm
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    long countByExample(ZybmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zybm
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int deleteByExample(ZybmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zybm
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int deleteByPrimaryKey(String zybmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zybm
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int insert(Zybm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zybm
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int insertSelective(Zybm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zybm
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    List<Zybm> selectByExample(ZybmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zybm
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    Zybm selectByPrimaryKey(String zybmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zybm
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Zybm record, @Param("example") ZybmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zybm
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByExample(@Param("record") Zybm record, @Param("example") ZybmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zybm
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByPrimaryKeySelective(Zybm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zybm
     *
     * @mbg.generated Tue Mar 27 14:38:52 CST 2018
     */
    int updateByPrimaryKey(Zybm record);
}